spring:
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include:  metrics, prometheus

    health:
      show-details: always